[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "macro-tracker"
version = "0.1.0"

[project.scripts]
mtracker = "mtracker.main:main"

[tool.setuptools.packages.find]
where = ["src"]
